// <auto-generated />
using System;
using Health.Persistence.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Health.Persistence.Data.Migrations
{
    [DbContext(typeof(HealthCareDbContext))]
    partial class HealthCareDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Health.Domain.Entities.AppointmentModule.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorGeneratedSlotsId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorProfileId")
                        .HasColumnType("int");

                    b.Property<int>("PatientProfileId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorGeneratedSlotsId")
                        .IsUnique();

                    b.HasIndex("DoctorProfileId");

                    b.HasIndex("PatientProfileId");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("Health.Domain.Entities.DoctorModule.DoctorGeneratedSlots", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorProfileId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorScheduleId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("SlotDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorProfileId");

                    b.HasIndex("DoctorScheduleId");

                    b.ToTable("DoctorGeneratedSlots", (string)null);
                });

            modelBuilder.Entity("Health.Domain.Entities.DoctorModule.DoctorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ClinicLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorPictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicalLicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneClinc")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<decimal>("PriceConsultation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SyndicateCardUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("int");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DoctorProfiles", (string)null);
                });

            modelBuilder.Entity("Health.Domain.Entities.DoctorModule.DoctorSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("DoctorProfileId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("SlotDurationMinutes")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DoctorProfileId");

                    b.ToTable("DoctorSchedules", (string)null);
                });

            modelBuilder.Entity("Health.Domain.Entities.PatientModule.ChronicDisease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ChronicDisease", (string)null);
                });

            modelBuilder.Entity("Health.Domain.Entities.PatientModule.PatientChronicDisease", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("ChronicDiseaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DiagnosedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("PatientId", "ChronicDiseaseId");

                    b.HasIndex("ChronicDiseaseId");

                    b.ToTable("PatientChronicDisease", (string)null);
                });

            modelBuilder.Entity("Health.Domain.Entities.PatientModule.PatientProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PatientProfiles", (string)null);
                });

            modelBuilder.Entity("Health.Domain.Entities.AppointmentModule.Appointment", b =>
                {
                    b.HasOne("Health.Domain.Entities.DoctorModule.DoctorGeneratedSlots", "DoctorGeneratedSlots")
                        .WithOne()
                        .HasForeignKey("Health.Domain.Entities.AppointmentModule.Appointment", "DoctorGeneratedSlotsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Health.Domain.Entities.DoctorModule.DoctorProfile", "DoctorProfile")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Health.Domain.Entities.PatientModule.PatientProfile", "PatientProfile")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DoctorGeneratedSlots");

                    b.Navigation("DoctorProfile");

                    b.Navigation("PatientProfile");
                });

            modelBuilder.Entity("Health.Domain.Entities.DoctorModule.DoctorGeneratedSlots", b =>
                {
                    b.HasOne("Health.Domain.Entities.DoctorModule.DoctorProfile", "DoctorProfile")
                        .WithMany("DoctorGeneratedSlots")
                        .HasForeignKey("DoctorProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Health.Domain.Entities.DoctorModule.DoctorSchedule", "DoctorSchedule")
                        .WithMany("DoctorGeneratedSlots")
                        .HasForeignKey("DoctorScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorProfile");

                    b.Navigation("DoctorSchedule");
                });

            modelBuilder.Entity("Health.Domain.Entities.DoctorModule.DoctorProfile", b =>
                {
                    b.OwnsOne("Health.Domain.Entities.DoctorModule.Address", "Address", b1 =>
                        {
                            b1.Property<int>("DoctorProfileId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("DoctorProfileId");

                            b1.ToTable("DoctorProfiles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DoctorProfileId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Health.Domain.Entities.DoctorModule.DoctorSchedule", b =>
                {
                    b.HasOne("Health.Domain.Entities.DoctorModule.DoctorProfile", "DoctorProfile")
                        .WithMany("DoctorSchedule")
                        .HasForeignKey("DoctorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorProfile");
                });

            modelBuilder.Entity("Health.Domain.Entities.PatientModule.PatientChronicDisease", b =>
                {
                    b.HasOne("Health.Domain.Entities.PatientModule.ChronicDisease", "ChronicDisease")
                        .WithMany("PatientChronicDiseases")
                        .HasForeignKey("ChronicDiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Health.Domain.Entities.PatientModule.PatientProfile", "Patient")
                        .WithMany("PatientChronicDiseases")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChronicDisease");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Health.Domain.Entities.PatientModule.PatientProfile", b =>
                {
                    b.OwnsOne("Health.Domain.Entities.DoctorModule.Address", "Address", b1 =>
                        {
                            b1.Property<int>("PatientProfileId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.HasKey("PatientProfileId");

                            b1.ToTable("PatientProfiles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PatientProfileId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Health.Domain.Entities.DoctorModule.DoctorProfile", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorGeneratedSlots");

                    b.Navigation("DoctorSchedule");
                });

            modelBuilder.Entity("Health.Domain.Entities.DoctorModule.DoctorSchedule", b =>
                {
                    b.Navigation("DoctorGeneratedSlots");
                });

            modelBuilder.Entity("Health.Domain.Entities.PatientModule.ChronicDisease", b =>
                {
                    b.Navigation("PatientChronicDiseases");
                });

            modelBuilder.Entity("Health.Domain.Entities.PatientModule.PatientProfile", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("PatientChronicDiseases");
                });
#pragma warning restore 612, 618
        }
    }
}
